platform :ios, '9.0'

#use_frameworks!

target 'MCUIKit_Example' do
  pod 'MCUIKit', :path => '../'
  pod 'Masonry'
  pod 'MLeaksFinder'

  target 'MCUIKit_Tests' do
    inherit! :search_paths

    
  end
end
