# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
notifications:
  email: false
before_install:
- pod install --project-directory=Example
script: 
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MCUIKit.xcworkspace -scheme MCUIKit_Example -sdk iphonesimulator -destination 'name=iPhone X' ONLY_ACTIVE_ARCH=NO | xcpretty -c
