# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
xcode_workspace: Exmple/MCUIKit.xcworkspace
xcode_scheme : MCUIKit_Tests
cache: cocoapods
podfile: Example/Podfile
before_install:
- pod install
script: 
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/MCUIKit.xcworkspace -scheme MCUIKit-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
